// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fouqsvrlfghoebkhhxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvdXFzdnJsZmdob2Via2hoeGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTU4NTAsImV4cCI6MjA3MDY3MTg1MH0.YtTk32xe1P0WzlzzsL8DsXJScVu2CwKLQXi37iQ-3Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});